### PR TITLE
Mostly fixes and 2 minor features

### PR DESCRIPTION
**Pull request by rlcevg**

### CODE REVIEW

**Comment by abma** [comment]
wrong branch, this should have gone into spring:develop.

**Comment by abma** [comment]
aww, sorry, i was at the wrong repo :see_no_evil:

**Comment by abma** [comment]
time for vacation it seems! :-)

**Comment by lhog** [comment]
Yeah I got misled by github interface too in the same way. :)
Have a great Xmas break!

**Comment by abma** [comment]
Thanks, a late merry christmas! :-)

**Pull request merged**
