### PR TITLE
Update CircuitAI {1.0.7}

### PR DESCRIPTION
**Pull request by rlcevg**
1) Fix https://github.com/rlcevg/CircuitAI/issues/104
2) Remove boost dependency

----

Says "Can't automatically merge" and that's most likely i didn't pull duplicated commits after last PR-merge.
So anyone knows the proper way to develop in original repository and then update forked one? Should _fork_ just "git pull" from original repo?

### CODE REVIEW

**Comment by rlcevg** [comment]
Ok, seems i broke the usual git workflow:
1) _git pull_ out of foreign repository
2) make a branch a do all changes inside that branch
3) create PR with local branch
4) repeat (1) for new feature

I was coding everything in single branch _master_
Now have to figure out how to fix current state...

**Comment by abma** [comment]
hu? for a pull request this basically doesn't matter. What matters is the target branch but there is only one for an AI. :-)

**Comment by rlcevg** [comment]
Ok, so i still don't understand the issue.
Until https://github.com/spring/CircuitAI/pull/7 everything worked fine, no duplicate commits.
https://github.com/spring/CircuitAI/pull/7 introduced _duplicates_ or rather merged into spring with different hash:
1) original: https://github.com/rlcevg/CircuitAI/commit/cfac2ef83ffc73abb8439159a825d95af70b11f1 => spring: https://github.com/spring/CircuitAI/commit/fbabea3b3e2ca1f6f7fe90941c545bf6a45d8132
  Bump version {1.0.5}. Reduce memory usage: on-demand height initializ…
2) original: https://github.com/rlcevg/CircuitAI/commit/c73fdcb7a03361d7c361636a45accd3597ea600b => spring: https://github.com/spring/CircuitAI/commit/82921a1d1b198efb943453ef5d57ea29081855b0
  Optimize enemy->GetPos. Don't move while jumping. Fix elevation for m…

**Comment by abma** [comment]
thats because of the way how it was merged:

https://github.com/spring/CircuitAI/commit/fbabea3b3e2ca1f6f7fe90941c545bf6a45d8132
"rlcevg authored and ashdnazg committed"

**Comment by rlcevg** [comment]
Looks like. Seems now i have to _git pull_ from spring to rlcevg again and (squash or drop?) my original commits. And then proceed with git workflow described above (steps 1-4) to decrease chance of such happenings.

**Pull request closed without merging**
