### PR TITLE
Update CircuitAI {1.0.7}

### PR DESCRIPTION
**Pull request by rlcevg**
1) Fix https://github.com/rlcevg/CircuitAI/issues/104
2) Remove boost dependency

### CODE REVIEW

**Comment by abma** [comment]
looks good now?!

**Comment by rlcevg** [comment]
Yep, thanks! I guess hoko used some strange (windows?) software or merged manually, because there are no additional "Merge pull request #10 from rlcevg/f0" for his actions. So generally i should stick to branching code for PRs.

**Comment by abma** [comment]
i guess it was a rebase which is possible in the github webgui, too.

**Comment by abma** [comment]
the next time you could just open a mantis ticket and ask for an update of the submodule to the current version or a specific commit and we'll update the spring and this repo.

**Comment by abma** [comment]
(in the hope it works better)

**Pull request merged**
